spring:
  datasource:
    url: jdbc:h2:D:\35SCJ\spring\fiapcervejariabatch;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap

file:
  path: D:\35SCJ\spring\cervejaria-batch-tasklet.zip
  input: classpath:pessoa.txt